name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set working directory
        run: cd Sample-timeline/e2e-tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # group: "All tests"
          headed: false
          record: false
          parallel: false
          config: baseUrl="http://planning-staging.timeline.co/"
